baseURL = "https://lunchbag.ca/"
languageCode = "en-us"
title = "lunchbag"
theme = "v1"
paginate = "100"

[params]
  author = "Jen Yip"
  description = "Blog by Jen Yip, founder of Lunch Money"

[permalinks]
  posts = "/:filename/"

[markup.goldmark.renderer]
  unsafe= true

[services.rss]
  limit = 20